version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: ToDo_postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  mysql:
    image: mysql:latest
    container_name: ToDo_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: todo
      MYSQL_USER: user
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  pg_data:
  mysql_data: